7_1.out: 7_1.cpp
	g++ -Wall -Wextra -Ofast -march=native -mtune=native -std=c++20 -o 7_1.out 7_1.cpp

7_1: 7_1.out
	./7_1.out

7_2.out: 7_2.cpp
	g++ -Wall -Wextra -Ofast -march=native -mtune=native -std=c++20 -o 7_2.out 7_2.cpp

7_2: 7_2.out
	./7_2.out

clean:
	rm -rf *.out