1_1.out: 1_1.cpp
	g++ -Wall -Wextra -Ofast -march=native -mtune=native -std=c++20 -o 1_1.out 1_1.cpp

1_1: 1_1.out
	./1_1.out

1_2.out: 1_2.cpp
	g++ -Wall -Wextra -Ofast -march=native -mtune=native -std=c++20 -o 1_2.out 1_2.cpp

1_2: 1_2.out
	./1_2.out

clean:
	rm -rf *.out